image: plusangel/grpc-cplusplus-ubuntu18

build:
  script:
    - git clone https://angelos.p:$PASSWORD@gitlab.com/innotecuk/grpc-comms.git
    - cd grpc-comms/
    - mkdir -p build && cd build
    - cmake ..
    - make
