image: ubuntu:18.04

before_script:
  - apt-get update 
  - apt-get install -y build-essential autoconf libtool git pkg-config curl
  - apt-get install -y automake libtool curl make g++ unzip
  - apt-get clean
