stages:
  - build
  - test

image: plusangel/grpc-cplusplus-ubuntu18:0.1.0

before_script:
  - apt-get update 
  - apt-get install -y cmake libgtest-dev
  - apt-get clean
  - cd /usr/src/gtest
  - cmake CMakeLists.txt && make
  - cp *.a /usr/lib
  - cd ~
  - git clone https://github.com/jbeder/yaml-cpp.git
  - cd yaml-cpp
  - mkdir build && cd build
  - cmake .. && make && make install


build:
  stage: build
  script:
    - git clone https://angelos.p:$PASSWORD@gitlab.com/innotecuk/grpc-comms.git
    - cd grpc-comms/
    - mkdir -p build && cd build
    - cmake .. && make

testing:
  stage: test
  script:
    - git clone https://angelos.p:$PASSWORD@gitlab.com/innotecuk/grpc-comms.git
    - cd grpc-comms/
    - mkdir -p build && cd build
    - cmake .. && make && make tests
    - cd ..
    - ./startup.sh &
    - cd build
    - ctest