image: grpc/cxx

before_script:
  libraries-setup:
    - apt-get update 
    - apt-get install -y cmake libgtest-dev
    - apt-get clean

  gtest-build:
    - cd /usr/src/gtest
    - cmake CMakeLists.txt
    - make
    - cp *.a /usr/lib

build:
  script:
    - git clone https://angelos.p:$PASSWORD@gitlab.com/innotecuk/grpc-comms.git
    - cd grpc-comms/
    - mkdir -p build && cd build
    - cmake ..
    - make
