image: ubuntu:18.04

before_script:
  - apt-get update 
  - apt-get install -y build-essential autoconf libtool git pkg-config curl
  - apt-get install -y automake libtool curl make g++ unzip
  - apt-get clean

grpc_build:
  script:
    - git clone -b v1.21.x https://github.com/grpc/grpc /var/local/git/grpc && \
      cd /var/local/git/grpc && \
      git submodule update --init && \
      echo "--- installing protobuf ---" && \
      cd third_party/protobuf && \
      git submodule update --init && \
      ./autogen.sh && ./configure --enable-shared && \
      make -j$(nproc) && make -j$(nproc) check && make install && make clean && ldconfig && \
      echo "--- installing grpc ---" && \
      cd /var/local/git/grpc && \
      make -j$(nproc) && make install && make clean && ldconfig && \
      rm -rf /var/local/git/grpc
    
build:
  script:
    - mkdir ~/platformComms
    - cd ~/platformComms
    - git clone https://angelos.plastropoulos@innotecuk.com:$PASSWORD@gitlab.com/innotecuk/grpc-comms.git